name: Build image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      build-target:
        required: true
        type: string
      image-file: #sr-api-backoffice.tar
        required: true
        type: string
      image-name: #api-backoffice
        required: true
        type: string
      test-project: #StreetNameRegistry.Tests
        required: true
        type: string
      build-project: #StreetNameRegistry.Api.BackOffice
        required: true
        type: string
      semver:
        required: true
        type: string
      docker-compose-file-path:
          required: false
          type: string
      docker-compose-prefix:
          required: false
          type: string

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check version
        shell: bash
        run: echo $SEMVER
        env:
          SEMVER: ${{ inputs.semver }}

      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Remove old docker containers
        if: github.event.inputs.inputs.docker-compose-file-path != ''
        run: docker container ls -a --filter "name=${{inputs.docker-compose-prefix}}*" --format "{{.ID}}" | awk 'NR>1' | xargs --no-run-if-empty docker container rm
        shell: bash
  
      - name: Remove old docker volumes
        if: github.event.inputs.inputs.docker-compose-file-path != ''
        run: docker volume ls | grep ${{inputs.docker-compose-prefix}} | awk '{print $2}' | xargs --no-run-if-empty docker volume rm || true
        shell: bash
  
      - name: Remove ol docker network
        if: github.event.inputs.inputs.docker-compose-file-path != ''
        run: docker network ls | grep ${{inputs.docker-compose-prefix}} | awk 'NR>0 {print $2}' | xargs --no-run-if-empty docker network rm || true
        shell: bash

      - name: docker-compose
        if: github.event.inputs.inputs.docker-compose-file-path != ''
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ${{ inputs.docker-compose-file-path }}

      - name: Cache Paket
        uses: actions/cache@v3
        env:
          cache-name: cache-paket
        with:
          path: packages
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('paket.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}

      - name: .NET version
        shell: bash
        run: dotnet --info

      - name: Restore dotnet tools
        shell: bash
        run: |
          dotnet tool restore

      - name: Paket install
        shell: bash
        run: dotnet paket install

      - name: Paket restore
        shell: bash
        run: dotnet paket restore

      - name: Dotnet restore tests
        shell: bash
        run: dotnet restore test/${{ inputs.test-project }} --runtime linux-x64

      - name: Dotnet build tests
        shell: bash
        run: dotnet build --no-restore --runtime 'linux-x64' --self-contained test/${{ inputs.test-project }}

      - name: Run all tests
        run: dotnet test test/${{ inputs.test-project }}

      - name: Dotnet restore
        shell: bash
        run: dotnet restore src/${{ inputs.build-project }} --runtime linux-x64
      
      - name: Set Assembly Versions
        shell: bash
        run: CI_BUILD_NUMBER=$SEMVER ./build.sh SetAssemblyVersions
        env:          
          SEMVER: ${{ inputs.semver }}

      - name: Dotnet build
        shell: bash
        run: dotnet build --no-restore --runtime 'linux-x64' --self-contained src/${{ inputs.build-project }}

      - name: Dotnet publish
        shell: bash
        run: dotnet publish -o dist/${{ inputs.build-project }}/linux --no-build --no-restore --runtime 'linux-x64' -p:PublishReadyToRun=true --self-contained src/${{ inputs.build-project }}

      - name: Containerize
        shell: bash
        run: CI_BUILD_NUMBER=$SEMVER ./build.sh ${{ inputs.build-target }}
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          SEMVER: ${{ inputs.semver }}

      - name: Show images
        shell: bash
        run: docker images

      - name: Save Image
        if: inputs.semver != 'none'
        shell: bash
        run: docker image save $BUILD_DOCKER_REGISTRY/${{ inputs.registry }}/${{ inputs.image-name }}:$SEMVER -o ~/${{ inputs.image-file}}
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          SEMVER: ${{ inputs.semver }}

      - name: Upload image
        if: inputs.semver != 'none'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.image-name }}-${{ inputs.semver }}
          path: ~/${{ inputs.image-file }}

      # - name: Shows logs ACM container
      #   if: ${{ failure() }}
      #   shell: bash
      #   run: |
      #     docker logs acm

      # - name: Shows logs elasticsearch container
      #   if: ${{ failure() }}
      #   shell: bash
      #   run: |
      #     docker logs elasticsearch

      # - name: Shows logs db container
      #   if: ${{ failure() }}
      #   shell: bash
      #   run: |
      #     docker logs db

      # - name: Shows logs minio container
      #   if: ${{ failure() }}
      #   shell: bash
      #   run: |
      #     docker logs minio